/* V96 - Module Họp không giấy: chỉ hiển thị hồ sơ đã tạo/liên kết
   File này chạy trong cùng trang Portal Lịch công tác, dùng chung APP/api/modal/helper. */
// ===== Module Họp không giấy =====
function hkgCanManage(){ return hasRole(ROLE_EDIT); }
function hkgStatusLabel(s){ const m={DONE:'Hoàn thành',WAIT_DOCS:'Chờ tài liệu',WAIT_ATTEND:'Chờ điểm danh',WAIT_MINUTES:'Chờ biên bản',WAIT_CONCLUSION:'Chờ kết luận'}; return m[s]||s||'Đang xử lý'; }
function hkgStatusClass(s){ return s==='DONE'?'done':(s==='OVERDUE'?'late':'wait'); }
async function renderHkgModule(){
  const box=$('screen-hkg'); if(!box) return;
  if(APP.currentScreen!=='hkg' && APP.hkg.loaded) return;
  if(!APP.hkg.loaded || APP.hkg.view==='list') return await renderHkgList();
  if(APP.hkg.view==='detail') return await renderHkgDetail();
  if(APP.hkg.view==='groups') return await renderHkgGroups();
}
async function renderHkgList(){
  const box=$('screen-hkg'); if(!box) return;
  box.innerHTML='<div class="loading"><div class="spin"></div><span>Đang tải module Họp không giấy...</span></div>';
  try{
    const res=await api('getHkgMeetings',{showPast:true,limit:300});
    APP.hkg.dashboard=res.dashboard||{}; APP.hkg.meetings=res.meetings||[]; APP.hkg.loaded=true; APP.hkg.view='list';
    const d=APP.hkg.dashboard;
    box.innerHTML=`<div class="hkg-shell">
      <div class="hkg-hero"><div><h2>📋 Họp không giấy</h2><p>Chỉ hiển thị các cuộc họp đã được tạo hồ sơ Họp không giấy từ Lịch công tác. Vào từng lịch họp và bấm “📋 Hồ sơ họp” để tạo/liên kết.</p></div><div class="hkg-toolbar"><button class="btn ghost sm" onclick="renderHkgGroups()">👥 Nhóm dự họp</button><button class="btn primary sm" onclick="hkgReload()">↻ Tải lại</button></div></div>
      <div class="hkg-stat-grid">
        ${hkgStat('Tổng hồ sơ',d.total||0)}${hkgStat('Chờ tài liệu',d.waitingDocs||0)}${hkgStat('Chờ điểm danh',d.waitingAttendance||0)}${hkgStat('Chờ biên bản',d.waitingMinutes||0)}${hkgStat('Chờ kết luận',d.waitingConclusion||0)}${hkgStat('Hoàn thành',d.completed||0)}
      </div>
      <div class="panel"><div class="panel-h"><h3>Danh sách hồ sơ họp</h3></div><div class="panel-b">
        <div class="hkg-toolbar" style="margin-bottom:12px"><input id="hkgKw" placeholder="Tìm mã lịch, nội dung, chủ trì..." oninput="hkgFilterList()"><select id="hkgFilterStatus" onchange="hkgFilterList()"><option value="all">Tất cả trạng thái</option><option value="WAIT_DOCS">Chờ tài liệu</option><option value="WAIT_ATTEND">Chờ điểm danh</option><option value="WAIT_MINUTES">Chờ biên bản</option><option value="WAIT_CONCLUSION">Chờ kết luận</option><option value="DONE">Hoàn thành</option></select></div>
        <div id="hkgMeetingList">${hkgMeetingListHtml(APP.hkg.meetings)}</div>
      </div></div>
    </div>`;
  }catch(e){box.innerHTML=`<div class="msg err">${esc(e.message)}</div>`;}
}
function hkgStat(label,val){return `<div class="hkg-stat"><b>${esc(val)}</b><span>${esc(label)}</span></div>`;}
function hkgMeetingListHtml(arr){
  if(!arr||!arr.length)return '<div class="empty"><b>Chưa có hồ sơ Họp không giấy.</b><br>Module này chỉ hiển thị các cuộc họp đã được tạo/liên kết. Hãy vào Lịch công tác, mở lịch cần xử lý và bấm <b>📋 Hồ sơ họp</b>.</div>';
  return `<div class="table-wrap hkg-table-mobile"><table class="tbl"><thead><tr><th>Mã</th><th>Ngày họp</th><th>Nội dung</th><th>Chủ trì</th><th>Tài liệu</th><th>Điểm danh</th><th>Biên bản</th><th>Kết luận</th><th>Trạng thái</th><th></th></tr></thead><tbody>${arr.map(x=>`<tr>
    <td data-label="Mã"><b class="mono">${esc(x.meetingId)}</b></td><td data-label="Ngày">${esc(dateVNShort(x.ngayHienThi||x.ngayBatDau))}<br><span class="muted">${esc(timeRange(x))}</span></td><td data-label="Nội dung"><b>${esc(x.noiDung)}</b><br><span class="muted">${esc(x.diaDiem||'')}</span></td><td data-label="Chủ trì">${esc(x.chuTri||'')}</td><td data-label="Tài liệu">${esc(x.fileCount||0)}</td><td data-label="Điểm danh">${esc(x.attendanceDone||0)}/${esc(x.participantCount||0)}</td><td data-label="Biên bản">${x.hasMinutes?'Có':'Chưa'}</td><td data-label="Kết luận">${esc(x.conclusionCount||0)}</td><td data-label="Trạng thái"><span class="hkg-status ${hkgStatusClass(x.hkgStatus)}">${esc(hkgStatusLabel(x.hkgStatus))}</span></td><td data-label="Thao tác"><button class="btn primary xs" onclick="openHkgDetail('${esc(x.meetingId)}')">Mở hồ sơ</button></td>
  </tr>`).join('')}</tbody></table></div>`;
}
function hkgFilterList(){const kw=normalizeText(($('hkgKw')?.value||''));const st=$('hkgFilterStatus')?.value||'all';let arr=(APP.hkg.meetings||[]).filter(x=>(st==='all'||x.hkgStatus===st));if(kw)arr=arr.filter(x=>normalizeText([x.meetingId,x.noiDung,x.chuTri,x.diaDiem].join(' ')).includes(kw));$('hkgMeetingList').innerHTML=hkgMeetingListHtml(arr);}
async function hkgReload(){APP.hkg.loaded=false;APP.hkg.view='list';await renderHkgList();}
async function openHkgDetail(meetingId){
  try{
    // V96: mở từ Lịch công tác thì tạo/liên kết hồ sơ Họp không giấy trước.
    await api('createHkgProfile',{meetingId:meetingId});
    APP.hkg.loaded=false;
    APP.hkg.view='detail';APP.hkg.meetingId=meetingId;APP.hkg.detail=null;APP.hkg.tab='info';
    await go('hkg');
  }catch(e){alert(e.message||'Không tạo/mở được hồ sơ Họp không giấy.');}
}
async function renderHkgDetail(){
  const box=$('screen-hkg'); if(!box) return; const id=APP.hkg.meetingId; if(!id){APP.hkg.view='list';return renderHkgList();}
  box.innerHTML='<div class="loading"><div class="spin"></div><span>Đang tải hồ sơ họp...</span></div>';
  try{const res=await api('getHkgDetail',{meetingId:id,autoCreate:true}); APP.hkg.detail=res; const m=res.meeting||{}; box.innerHTML=`<div class="hkg-shell">
    <div class="hkg-detail-head"><div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><div class="hkg-detail-title">${esc(m.meetingId)} · ${esc(m.noiDung||'Hồ sơ họp')}</div><div class="muted">${esc(dateVNShort(m.ngayHienThi||m.ngayBatDau))} · ${esc(timeRange(m))} · ${esc(m.diaDiem||'')}</div></div><div class="hkg-toolbar"><button class="btn ghost sm" onclick="APP.hkg.view='list';renderHkgList()">← Danh sách</button><button class="btn sm" onclick="openDetail('${esc(id)}')">👁 Lịch gốc</button></div></div></div>
    <div class="hkg-tabs">${['info|Thông tin','docs|Tài liệu','att|Điểm danh','op|Ý kiến','vote|Biểu quyết','min|Biên bản','con|Kết luận','his|Lịch sử'].map(s=>{const [k,l]=s.split('|');return `<button class="hkg-tab ${APP.hkg.tab===k?'active':''}" onclick="hkgSetTab('${k}')">${l}</button>`}).join('')}</div>
    <div id="hkgTabBody">${hkgTabHtml()}</div>
  </div>`; hkgMaybeStartVoteTimer();}catch(e){box.innerHTML=`<div class="msg err">${esc(e.message)}</div>`;}
}
function hkgSetTab(t){APP.hkg.tab=t; const b=$('hkgTabBody'); if(b)b.innerHTML=hkgTabHtml(); document.querySelectorAll('.hkg-tab').forEach(x=>x.classList.remove('active')); hkgMaybeStartVoteTimer();}
function hkgTabHtml(){const r=APP.hkg.detail||{}, m=r.meeting||{}; const t=APP.hkg.tab||'info';
  if(t==='info')return `<div class="hkg-grid2"><div class="hkg-card"><h4>Thông tin cuộc họp</h4>${hkgInfoRow('Mã lịch',m.meetingId)}${hkgInfoRow('Nội dung',m.noiDung)}${hkgInfoRow('Thời gian',dateVNShort(m.ngayHienThi||m.ngayBatDau)+' · '+timeRange(m))}${hkgInfoRow('Địa điểm',m.diaDiem)}${hkgInfoRow('Chủ trì',m.chuTri)}${hkgInfoRow('Thành phần',m.thanhPhan)}</div><div class="hkg-card"><h4>Thao tác nhanh</h4><div class="hkg-mini-list"><button class="btn primary" onclick="hkgSetTab('att')">✅ Điểm danh</button><button class="btn" onclick="hkgSetTab('vote')">🗳 Biểu quyết</button><button class="btn" onclick="hkgSetTab('min')">📝 Biên bản</button><button class="btn" onclick="hkgSetTab('con')">📌 Kết luận</button></div></div></div>`;
  if(t==='docs')return `<div class="hkg-card"><h4>Tài liệu họp</h4>${(r.files||[]).length?`<div class="hkg-mini-list">${r.files.map(f=>`<div class="hkg-mini-item"><b>${esc(f.fileName||f.name||'Tài liệu')}</b><br><span class="muted">${esc(f.fileType||'')}</span><div style="margin-top:6px"><a class="btn xs primary" target="_blank" href="${esc(f.fileUrl||f.url||'#')}">Mở file</a></div></div>`).join('')}</div>`:'<div class="empty">Chưa có tài liệu họp.</div>'}<div style="margin-top:12px"><button class="btn" onclick="openDetail('${esc(m.meetingId)}')">Upload/xem tài liệu trong lịch gốc</button></div></div>`;
  if(t==='att')return hkgAttendanceHtml(r);
  if(t==='op')return hkgOpinionHtml(r);
  if(t==='vote')return hkgVoteHtml(r);
  if(t==='min')return hkgMinutesHtml(r);
  if(t==='con')return hkgConclusionHtml(r);
  if(t==='his')return `<div class="hkg-card"><h4>Lịch sử xử lý</h4>${(r.history||[]).length?`<div class="hkg-mini-list">${r.history.map(h=>`<div class="hkg-mini-item"><b>${esc(h.action)}</b> · <span class="muted">${esc(h.createdAt)}</span><br>${esc(h.fullname||h.username||'')} ${h.newValue?`<br><span>${esc(h.newValue)}</span>`:''}</div>`).join('')}</div>`:'<div class="empty">Chưa có lịch sử.</div>'}</div>`;
  return '';
}
function hkgInfoRow(k,v){return `<div class="m-meta-row"><span class="label">${esc(k)}</span><span>${esc(v||'')}</span></div>`;}
function hkgAttendanceHtml(r){const arr=r.attendance||[];return `<div class="hkg-card"><h4>Thành phần / Điểm danh</h4>${arr.length?`<div class="table-wrap hkg-table-mobile"><table class="tbl"><thead><tr><th>Họ tên</th><th>Đơn vị</th><th>Nguồn</th><th>Trạng thái</th><th>Ghi chú</th></tr></thead><tbody>${arr.map(a=>`<tr><td data-label="Họ tên"><b>${esc(a.fullname||a.username)}</b></td><td data-label="Đơn vị">${esc(a.donVi||'')}</td><td data-label="Nguồn">${esc(a.sourceName||a.roleInMeeting||'')}</td><td data-label="Trạng thái"><select onchange="saveHkgAttendance('${esc(a.username)}',this.value)">${['Chưa xác nhận','Có mặt','Vắng có lý do','Vắng không lý do','Dự thay','Đến muộn'].map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td data-label="Ghi chú"><input value="${esc(a.note||'')}" onchange="saveHkgAttendance('${esc(a.username)}',null,this.value)" placeholder="Ghi chú"></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Chưa có thành phần. Có thể dùng nhóm dự họp để thêm thành phần.</div>'}<div style="margin-top:12px"><button class="btn" onclick="openHkgInviteModal()">👥 Chọn nhóm/gọi thêm</button></div></div>`;}
async function saveHkgAttendance(username,status,note){try{await api('saveHkgAttendance',{meetingId:APP.hkg.meetingId,username,status,note});}catch(e){alert(e.message)}}
function hkgOpinionHtml(r){return `<div class="hkg-grid2"><div class="hkg-card"><h4>Gửi ý kiến</h4><div class="hkg-form-row"><label>Loại ý kiến</label><select id="hkgOpType"><option>Trước họp</option><option>Trong họp</option><option>Sau họp</option></select></div><div class="hkg-form-row"><label>Nội dung</label><textarea id="hkgOpContent" placeholder="Nhập ý kiến..."></textarea></div><button class="btn primary" onclick="saveHkgOpinion()">Gửi ý kiến</button></div><div class="hkg-card"><h4>Danh sách ý kiến</h4>${(r.opinions||[]).length?`<div class="hkg-mini-list">${r.opinions.map(o=>`<div class="hkg-mini-item"><b>${esc(o.fullname||o.username)}</b> · <span class="muted">${esc(o.opinionType)} · ${esc(o.createdAt)}</span><br>${esc(o.content)}</div>`).join('')}</div>`:'<div class="empty">Chưa có ý kiến.</div>'}</div></div>`;}
async function saveHkgOpinion(){const content=($('hkgOpContent')?.value||'').trim(); if(!content)return alert('Nhập nội dung ý kiến.'); try{await api('saveHkgOpinion',{meetingId:APP.hkg.meetingId,opinionType:$('hkgOpType').value,content}); await hkgReloadDetail('op');}catch(e){alert(e.message)}}
function hkgVoteHtml(r){const votes=r.votes||[];return `<div class="hkg-grid2"><div class="hkg-card"><h4>Tạo biểu quyết</h4><div class="hkg-form-row"><label>Nội dung biểu quyết</label><input id="hkgVoteTitle" placeholder="Ví dụ: Thông qua dự thảo báo cáo..."></div><div class="hkg-form-row"><label>Lựa chọn</label><input id="hkgVoteOptions" value="Đồng ý;Không đồng ý;Không có ý kiến"></div><button class="btn primary" onclick="createHkgVote()">＋ Tạo biểu quyết</button></div><div class="hkg-card"><h4>Phiên biểu quyết</h4>${votes.length?`<div class="hkg-mini-list">${votes.map(v=>hkgVoteItem(v)).join('')}</div>`:'<div class="empty">Chưa có biểu quyết.</div>'}</div></div>`;}
function hkgVoteItem(v){const total=(v.total||0)||1;return `<div class="hkg-mini-item"><b>${esc(v.title)}</b><br><span class="hkg-status ${v.status==='OPEN'?'wait':'done'}">${v.status==='OPEN'?'Đang mở':'Đã đóng'}</span><div style="margin-top:8px">${(v.results||[]).map(x=>`<div style="display:flex;justify-content:space-between"><span>${esc(x.choice)}</span><b>${esc(x.count)}</b></div><div class="hkg-bar"><span style="width:${Math.round((x.count||0)*100/total)}%"></span></div>`).join('')}</div><div class="hkg-toolbar" style="margin-top:8px">${v.status==='OPEN'?`<button class="btn xs" onclick="submitHkgVote('${esc(v.voteId)}','Đồng ý')">Đồng ý</button><button class="btn xs" onclick="submitHkgVote('${esc(v.voteId)}','Không đồng ý')">Không đồng ý</button><button class="btn xs" onclick="submitHkgVote('${esc(v.voteId)}','Không có ý kiến')">Không ý kiến</button><button class="btn danger xs" onclick="closeHkgVote('${esc(v.voteId)}')">Đóng</button>`:`<button class="btn xs" onclick="openHkgVote('${esc(v.voteId)}')">Mở lại</button>`}</div></div>`;}
async function createHkgVote(){const title=($('hkgVoteTitle')?.value||'').trim(); if(!title)return alert('Nhập nội dung biểu quyết.'); try{await api('createHkgVote',{meetingId:APP.hkg.meetingId,title,options:($('hkgVoteOptions')?.value||'')}); await hkgReloadDetail('vote');}catch(e){alert(e.message)}}
async function submitHkgVote(voteId,choice){try{await api('submitHkgVote',{meetingId:APP.hkg.meetingId,voteId,choice}); await hkgReloadDetail('vote');}catch(e){alert(e.message)}}
async function closeHkgVote(voteId){try{await api('closeHkgVote',{voteId}); await hkgReloadDetail('vote');}catch(e){alert(e.message)}}
async function openHkgVote(voteId){try{await api('openHkgVote',{voteId}); await hkgReloadDetail('vote');}catch(e){alert(e.message)}}
function hkgMaybeStartVoteTimer(){ if(APP.hkg.voteTimer){clearInterval(APP.hkg.voteTimer);APP.hkg.voteTimer=null;} if(APP.currentScreen==='hkg'&&APP.hkg.view==='detail'&&APP.hkg.tab==='vote')APP.hkg.voteTimer=setInterval(()=>hkgReloadDetail('vote',true),5000); }
function hkgMinutesHtml(r){const min=r.minutes||{};return `<div class="hkg-card"><h4>Biên bản cuộc họp</h4><div class="hkg-form-row"><label>Tiêu đề</label><input id="hkgMinTitle" value="${esc(min.title||('Biên bản '+(r.meeting?.meetingId||'')))}"></div><div class="hkg-form-row"><label>Nội dung biên bản</label><textarea id="hkgMinContent" style="min-height:280px">${esc(min.contentText||hkgMinutesTemplate(r))}</textarea></div><div class="hkg-toolbar"><button class="btn primary" onclick="saveHkgMinutes()">Lưu biên bản</button><button class="btn" onclick="autoFillHkgMinutes()">Tự tổng hợp</button><button class="btn ok" onclick="exportHkgMinutes('pdf')">Xuất PDF</button><button class="btn" onclick="exportHkgMinutes('docx')">Xuất Word</button>${min.pdfFileUrl?`<a class="btn xs primary" target="_blank" href="${esc(min.pdfFileUrl)}">Mở PDF</a>`:''}${min.docxFileUrl?`<a class="btn xs" target="_blank" href="${esc(min.docxFileUrl)}">Mở Word</a>`:''}</div></div>`;}
function hkgMinutesTemplate(r){const m=r.meeting||{};return `BIÊN BẢN CUỘC HỌP\n\n1. Thông tin cuộc họp\n- Nội dung: ${m.noiDung||''}\n- Thời gian: ${dateVNShort(m.ngayHienThi||m.ngayBatDau)} ${timeRange(m)}\n- Địa điểm: ${m.diaDiem||''}\n- Chủ trì: ${m.chuTri||''}\n\n2. Thành phần tham dự\n- Tổng số được mời: ${(r.attendance||[]).length}\n- Có mặt: ${(r.attendance||[]).filter(x=>x.status==='Có mặt').length}\n\n3. Nội dung cuộc họp\n\n4. Ý kiến tham gia\n${(r.opinions||[]).map(o=>'- '+(o.content||'')).join('\n')}\n\n5. Kết quả biểu quyết\n${(r.votes||[]).map(v=>'- '+v.title).join('\n')}\n\n6. Kết luận cuộc họp\n${(r.conclusions||[]).map(c=>'- '+(c.content||'')).join('\n')}\n`;}
function autoFillHkgMinutes(){const t=$('hkgMinContent'); if(t)t.value=hkgMinutesTemplate(APP.hkg.detail||{});}
async function saveHkgMinutes(){try{await api('saveHkgMinutes',{meetingId:APP.hkg.meetingId,title:$('hkgMinTitle').value,contentText:$('hkgMinContent').value}); await hkgReloadDetail('min');}catch(e){alert(e.message)}}
async function exportHkgMinutes(type){try{await saveHkgMinutes(); const res=await api(type==='pdf'?'exportHkgMinutesPdf':'exportHkgMinutesDocx',{meetingId:APP.hkg.meetingId}); alert('Đã xuất '+(type==='pdf'?'PDF':'Word')); await hkgReloadDetail('min'); if(res.url)window.open(res.url,'_blank');}catch(e){alert(e.message)}}
function hkgConclusionHtml(r){return `<div class="hkg-grid2"><div class="hkg-card"><h4>Thêm kết luận</h4><div class="hkg-form-row"><label>Nội dung</label><textarea id="hkgConContent"></textarea></div><div class="hkg-form-row"><label>Người phụ trách</label><input id="hkgConAssignee" placeholder="Tên người phụ trách"></div><div class="hkg-form-row"><label>Hạn hoàn thành</label><input id="hkgConDue" type="date"></div><button class="btn primary" onclick="saveHkgConclusion()">Lưu kết luận</button></div><div class="hkg-card"><h4>Danh sách kết luận</h4>${(r.conclusions||[]).length?`<div class="hkg-mini-list">${r.conclusions.map(c=>`<div class="hkg-mini-item"><b>${esc(c.content)}</b><br><span class="muted">Phụ trách: ${esc(c.assigneeFullname||c.assigneeUsername||'')} · Hạn: ${esc(c.dueDate||'')}</span><br><span class="hkg-status ${c.status==='Hoàn thành'?'done':'wait'}">${esc(c.status||'Chưa thực hiện')}</span><div class="hkg-toolbar" style="margin-top:7px"><button class="btn xs" onclick="updateHkgConclusion('${esc(c.conclusionId)}','Đang thực hiện')">Đang làm</button><button class="btn xs ok" onclick="updateHkgConclusion('${esc(c.conclusionId)}','Hoàn thành')">Hoàn thành</button></div></div>`).join('')}</div>`:'<div class="empty">Chưa có kết luận.</div>'}</div></div>`;}
async function saveHkgConclusion(){const content=($('hkgConContent')?.value||'').trim(); if(!content)return alert('Nhập nội dung kết luận.'); try{await api('saveHkgConclusion',{meetingId:APP.hkg.meetingId,content,assigneeFullname:$('hkgConAssignee').value,dueDate:$('hkgConDue').value}); await hkgReloadDetail('con');}catch(e){alert(e.message)}}
async function updateHkgConclusion(id,status){try{await api('updateHkgConclusion',{meetingId:APP.hkg.meetingId,conclusionId:id,status}); await hkgReloadDetail('con');}catch(e){alert(e.message)}}
async function hkgReloadDetail(tab,silent){try{APP.hkg.tab=tab||APP.hkg.tab; const res=await api('getHkgDetail',{meetingId:APP.hkg.meetingId}); APP.hkg.detail=res; const b=$('hkgTabBody'); if(b)b.innerHTML=hkgTabHtml();}catch(e){if(!silent)alert(e.message)}}
async function renderHkgGroups(){const box=$('screen-hkg'); if(!box)return; APP.hkg.view='groups'; box.innerHTML='<div class="loading"><div class="spin"></div><span>Đang tải nhóm dự họp...</span></div>'; try{const res=await api('getMeetingGroups',{}); APP.hkg.groups=res.groups||[]; box.innerHTML=`<div class="hkg-shell"><div class="hkg-hero"><div><h2>👥 Nhóm người dự họp</h2><p>Tạo nhóm thành viên thường xuyên để mời họp nhanh.</p></div><div class="hkg-toolbar"><button class="btn ghost sm" onclick="APP.hkg.view='list';renderHkgList()">← Họp không giấy</button><button class="btn primary sm" onclick="openHkgGroupModal()">＋ Tạo nhóm</button></div></div><div class="panel"><div class="panel-b">${APP.hkg.groups.length?`<div class="table-wrap hkg-table-mobile"><table class="tbl"><thead><tr><th>Tên nhóm</th><th>Loại</th><th>Số TV</th><th>Trạng thái</th><th></th></tr></thead><tbody>${APP.hkg.groups.map(g=>`<tr><td data-label="Tên nhóm"><b>${esc(g.groupName)}</b><br><span class="muted">${esc(g.description||'')}</span></td><td data-label="Loại">${esc(g.groupType||'')}</td><td data-label="Số TV">${esc(g.memberCount||0)}</td><td data-label="Trạng thái">${esc(g.status||'Active')}</td><td><button class="btn xs primary" onclick="openHkgGroupModal('${esc(g.groupId)}')">Sửa</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Chưa có nhóm dự họp.</div>'}</div></div></div>`;}catch(e){box.innerHTML=`<div class="msg err">${esc(e.message)}</div>`;}}
async function openHkgGroupModal(groupId){let g={members:[]}; if(groupId){g=await api('getMeetingGroupDetail',{groupId});} const group=g.group||{}; APP.hkg.groupDraft={groupId:group.groupId||'',members:g.members||[]}; $('modal').classList.remove('hide'); $('modal').innerHTML=`<div class="modal-card"><div class="modal-h"><h3>${groupId?'Sửa':'Tạo'} nhóm dự họp</h3><button class="modal-close" onclick="closeModal()">✕</button></div><div class="modal-b"><div class="hkg-form-row"><label>Tên nhóm</label><input id="hkgGroupName" value="${esc(group.groupName||'')}"></div><div class="hkg-form-row"><label>Loại nhóm</label><select id="hkgGroupType"><option>Lãnh đạo</option><option>Phòng ban</option><option>Tổ công tác</option><option>Hội đồng</option><option>Khác</option></select></div><div class="hkg-form-row"><label>Mô tả</label><textarea id="hkgGroupDesc">${esc(group.description||'')}</textarea></div><div class="hkg-form-row"><label>Thêm thành viên</label><input id="hkgGroupUserSearch" placeholder="Gõ tên đăng nhập hoặc họ tên..." oninput="hkgSearchGroupUser(this.value)"><div id="hkgGroupUserSuggest"></div></div><div id="hkgGroupMembers">${hkgGroupMembersHtml()}</div><div class="toolbar" style="margin-top:15px"><button class="btn primary" onclick="saveHkgGroup()">Lưu nhóm</button><button class="btn ghost" onclick="closeModal()">Đóng</button></div></div></div>`; if(group.groupType)setTimeout(()=>$('hkgGroupType').value=group.groupType,0);}
function hkgGroupMembersHtml(){const arr=(APP.hkg.groupDraft&&APP.hkg.groupDraft.members)||[];return `<div>${arr.map(u=>`<span class="hkg-member-chip">${esc(u.fullname||u.username)} <button onclick="hkgRemoveGroupMember('${esc(u.username)}')">×</button></span>`).join('')||'<div class="empty">Chưa có thành viên.</div>'}</div>`;}
async function hkgSearchGroupUser(q){q=(q||'').trim(); if(q.length<2){$('hkgGroupUserSuggest').innerHTML='';return;} const res=await api('searchUsersForGroup',{keyword:q}); $('hkgGroupUserSuggest').innerHTML=(res.users||[]).slice(0,8).map(u=>`<div class="note-recipient-item" onclick='hkgAddGroupMember(${jss(u)})'><div class="note-recipient-main"><b>${esc(u.fullname)}</b><span>${esc(u.username)} · ${esc(u.donVi||'')}</span></div></div>`).join('');}
function hkgAddGroupMember(u){APP.hkg.groupDraft.members=APP.hkg.groupDraft.members||[]; if(!APP.hkg.groupDraft.members.some(x=>x.username===u.username))APP.hkg.groupDraft.members.push(u); $('hkgGroupMembers').innerHTML=hkgGroupMembersHtml(); $('hkgGroupUserSuggest').innerHTML=''; $('hkgGroupUserSearch').value='';}
function hkgRemoveGroupMember(username){APP.hkg.groupDraft.members=(APP.hkg.groupDraft.members||[]).filter(x=>x.username!==username); $('hkgGroupMembers').innerHTML=hkgGroupMembersHtml();}
async function saveHkgGroup(){const name=($('hkgGroupName')?.value||'').trim(); if(!name)return alert('Nhập tên nhóm.'); try{await api('saveMeetingGroup',{groupId:APP.hkg.groupDraft.groupId,groupName:name,groupType:$('hkgGroupType').value,description:$('hkgGroupDesc').value,members:APP.hkg.groupDraft.members||[]}); closeModal(); await renderHkgGroups();}catch(e){alert(e.message)}}
async function openHkgInviteModal(){const res=await api('getMeetingGroups',{}); APP.hkg.inviteDraft={groups:[],extras:[],excludes:[]}; $('modal').classList.remove('hide'); $('modal').innerHTML=`<div class="modal-card"><div class="modal-h"><h3>Chọn nhóm / gọi thêm / loại trừ</h3><button class="modal-close" onclick="closeModal()">✕</button></div><div class="modal-b"><div class="hkg-form-row"><label>Chọn nhóm</label><div>${(res.groups||[]).map(g=>`<label style="display:block;margin:6px 0"><input type="checkbox" value="${esc(g.groupId)}" onchange="hkgPreviewInvite()"> ${esc(g.groupName)} <span class="muted">(${esc(g.memberCount||0)} người)</span></label>`).join('')||'Chưa có nhóm.'}</div></div><div class="hkg-form-row"><label>Gọi thêm người</label><input id="hkgInviteSearch" placeholder="Gõ tên đăng nhập hoặc họ tên..." oninput="hkgSearchInviteUser(this.value)"><div id="hkgInviteSuggest"></div><div id="hkgInviteExtra"></div></div><div class="hkg-form-row"><label>Danh sách dự họp sau khi gộp</label><div id="hkgInvitePreview" class="hkg-mini-list"><div class="empty">Chọn nhóm để xem danh sách.</div></div></div><button class="btn primary" onclick="saveHkgInviteConfig()">Áp dụng vào thành phần dự họp</button></div></div>`;}
async function hkgPreviewInvite(){const groups=[...document.querySelectorAll('input[type="checkbox"]')].filter(x=>x.checked).map(x=>x.value); APP.hkg.inviteDraft.groups=groups; const res=await api('previewMeetingGroupMembers',{groupIds:groups,extras:APP.hkg.inviteDraft.extras||[],excludes:APP.hkg.inviteDraft.excludes||[]}); APP.hkg.inviteDraft.preview=res.members||[]; $('hkgInvitePreview').innerHTML=(res.members||[]).map(u=>`<div class="hkg-mini-item"><b>${esc(u.fullname||u.username)}</b><br><span class="muted">${esc(u.donVi||'')} · ${esc(u.sourceName||'')}</span> <button class="btn danger xs" onclick="hkgExcludeInvite('${esc(u.username)}')">Loại trừ</button></div>`).join('')||'<div class="empty">Chưa có thành viên.</div>';}
async function hkgSearchInviteUser(q){q=(q||'').trim(); if(q.length<2){$('hkgInviteSuggest').innerHTML='';return;} const res=await api('searchUsersForGroup',{keyword:q}); $('hkgInviteSuggest').innerHTML=(res.users||[]).slice(0,8).map(u=>`<div class="note-recipient-item" onclick='hkgAddInviteExtra(${jss(u)})'><div class="note-recipient-main"><b>${esc(u.fullname)}</b><span>${esc(u.username)} · ${esc(u.donVi||'')}</span></div></div>`).join('');}
function hkgAddInviteExtra(u){APP.hkg.inviteDraft.extras=APP.hkg.inviteDraft.extras||[]; if(!APP.hkg.inviteDraft.extras.some(x=>x.username===u.username))APP.hkg.inviteDraft.extras.push(u); $('hkgInviteExtra').innerHTML=(APP.hkg.inviteDraft.extras||[]).map(x=>`<span class="hkg-member-chip">${esc(x.fullname)}<button onclick="hkgRemoveInviteExtra('${esc(x.username)}')">×</button></span>`).join(''); $('hkgInviteSuggest').innerHTML=''; $('hkgInviteSearch').value=''; hkgPreviewInvite();}
function hkgRemoveInviteExtra(username){APP.hkg.inviteDraft.extras=(APP.hkg.inviteDraft.extras||[]).filter(x=>x.username!==username); hkgPreviewInvite();}
function hkgExcludeInvite(username){APP.hkg.inviteDraft.excludes=APP.hkg.inviteDraft.excludes||[]; if(!APP.hkg.inviteDraft.excludes.includes(username))APP.hkg.inviteDraft.excludes.push(username); hkgPreviewInvite();}
async function saveHkgInviteConfig(){try{await api('saveMeetingInviteConfig',{meetingId:APP.hkg.meetingId,groupIds:APP.hkg.inviteDraft.groups||[],extras:APP.hkg.inviteDraft.extras||[],excludes:APP.hkg.inviteDraft.excludes||[]}); closeModal(); await hkgReloadDetail('att');}catch(e){alert(e.message)}}
